### ISSUE TITLE
Issue with gfx files on local run

### ISSUE THREAD

**Issue by cunning-weasel** [GMH-Code/Quake-WASM#1]
Hey @GMH-Code ,

Not sure this is an issue as such, but didn't want to bother you with email. 

So firstly thanks for making this port possible! Big fan of the original, and all that. 

My issue is that once the build has run and the necessary .html, .js and .wasm files have been generated, upon entering the browser on localhost, errors are thrown regarding gfx files:

`Waiting for data to be restored...
Data restoration complete.
FindFile: can't find gfx/pop.lmp
Playing shareware version.
FindFile: can't find gfx.wad
Error: W_LoadWadFile: couldn't load gfx.wad`

this is with a shareware version (PAK0.PAK) added to the id1 dir. 

also added a gfx folder with empty gfx.wad and pop.lmp. Placed in WinQuake dir, data dir and even the id1 dir all to no avail. Will later purchase the full version of the game and use the PAK1.PAK from there. 

running on wsl and linux ubuntu has same issue. I guess I'm missing something super simple here..?

**Comment by GMH-Code** [comment]
Hi @cunning-weasel,

Thanks for the kind words.

*Quake-WASM* is case-sensitive.  The original Quake code expects PAK names (and other files) to be lowercase, but the files themselves are named in uppercase on the Windows releases.  Windows doesn't mind the difference, but Linux and WASM do.

Delete the `index.data` file from your build and rename `PAK0.PAK` -> `pak0.pak` and, if you have it, `PAK1.PAK` -> `pak1.pak`.  Then, re-run the build.  If you want to add other folders/files (mods, maps, sounds, etc.), then you'll likely need to rename those too.

There is a comment under the build instructions, but I probably should include it a little further up!

Let me know if that worked!

**Comment by cunning-weasel** [comment]
omg, I'm an idiot and you are right - rebuild and it worked. 

apologies and many thanks again for making this port possible !!
