### ISSUE TITLE
One more issue to be fixed until perfection

### ISSUE THREAD

**Issue by TheOneWhoAfksInTDS** [GMH-Code/Quake-WASM#3]
For some reason, the website doesn't take multiple files like pak0.pak and pak1.pak. This is the only other problem I've encountered other than the resolution, but at that point, the resolution is just pointless complaints. Thanks for at least reading this and fixing the other issue and I hope you have good day! 👍

**Comment by GMH-Code** [comment]
Hi @TheOneWhoAfksInTDS,

The file uploader on the website I'm hosting does accept more than one file, but you have to select them both at once.  I'm sure I'm stating the obvious and you already know you can do this in a desktop browser's file upload box with CTRL.  This might not be possible on the ChromeBook you mentioned though -- it will at least depend on the app managing file upload selections, and the browser itself, as to whether that's supported.

I've just tried this on an Android device with Fennec, and it does indeed look like you can only select one file regardless of the app managing the file selection.  I am sure I tested this before and it was fine, but online searches I've just done reveal that not all mobile browsers support it.

I'll change the behaviour when I have chance and state here when I've done it.  It should be a fairly simple JavaScript change.

**Comment by TheOneWhoAfksInTDS** [comment]
Oh, alright, thanks!

**Comment by GMH-Code** [comment]
Ok, I made the change.  Hard-refresh the page and you should be allowed to add more files, or clear the existing ones out.  You can still add multiple files at once if the browser/file browser allows it.  I'm keeping it simple for now though, so it doesn't have a list of files which you can add/delete/move, etc.

**Comment by TheOneWhoAfksInTDS** [comment]
Thanks! I'm glad to see you love this project enough to keep supporting it!
